"""SQLAlchemy ORM models for the central PostgreSQL schema.

Tables
------
persons            — identity / profile metadata
person_embeddings  — face / body reference vectors (FK → persons)
zones              — zone geometry per camera
events             — canonical event log (idempotency via unique event_id)
alerts             — delivery state of notifications (FK → events)
camera_configs     — per-camera runtime thresholds

All primary keys are client-generated UUIDs so records can be created
offline and later synced without ID conflicts.
"""

import uuid
from datetime import date, datetime, timezone

from sqlalchemy import (
    BigInteger,
    Boolean,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    LargeBinary,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class Base(DeclarativeBase):
    pass


# ── Persons ───────────────────────────────────────────────────────────────────

class Person(Base):
    __tablename__ = "persons"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    age: Mapped[int | None] = mapped_column(Integer, nullable=True)
    date_of_birth: Mapped[date | None] = mapped_column(Date, nullable=True)
    gender: Mapped[str | None] = mapped_column(String(50), nullable=True)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    room: Mapped[str | None] = mapped_column(String(255), nullable=True)
    status: Mapped[str] = mapped_column(
        String(50), nullable=False, default="active"
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    embeddings: Mapped[list["PersonEmbedding"]] = relationship(
        back_populates="person", cascade="all, delete-orphan"
    )
    events: Mapped[list["Event"]] = relationship(back_populates="person")


class PersonEmbedding(Base):
    __tablename__ = "person_embeddings"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    person_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("persons.id", ondelete="CASCADE"),
        nullable=False,
    )
    # Serialised float32 numpy array (numpy.ndarray.tobytes())
    embedding: Mapped[bytes] = mapped_column(LargeBinary, nullable=False)
    # "face" | "body"
    embedding_type: Mapped[str] = mapped_column(String(50), nullable=False)
    source: Mapped[str | None] = mapped_column(String(255), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )

    person: Mapped["Person"] = relationship(back_populates="embeddings")


# ── Zones ─────────────────────────────────────────────────────────────────────

class Zone(Base):
    __tablename__ = "zones"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    camera_id: Mapped[str] = mapped_column(String(255), nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    # "forbidden" | "entry" | "exit" | "roi"
    zone_type: Mapped[str] = mapped_column(String(50), nullable=False)
    # Polygon as {"points": [[x,y], ...]} — stored as JSONB
    geometry: Mapped[dict] = mapped_column(JSONB, nullable=False)
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    events: Mapped[list["Event"]] = relationship(back_populates="zone")


# ── Events ────────────────────────────────────────────────────────────────────

class Event(Base):
    __tablename__ = "events"
    __table_args__ = (
        UniqueConstraint("event_id", name="uq_events_event_id"),
        Index("ix_events_camera_track", "camera_id", "track_id"),
        Index("ix_events_person_id", "person_id"),
        Index("ix_events_occurred_at", "occurred_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    # Idempotency key — generated by the plugin or the service's outbox worker
    event_id: Mapped[str] = mapped_column(String(128), nullable=False)
    camera_id: Mapped[str] = mapped_column(String(255), nullable=False)
    track_id: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    # "detection" | "fall" | "zone_violation" | "prolongedDetection"
    event_type: Mapped[str] = mapped_column(String(100), nullable=False)
    cls: Mapped[str | None] = mapped_column(String(50), nullable=True)
    confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    bbox_x: Mapped[float | None] = mapped_column(Float, nullable=True)
    bbox_y: Mapped[float | None] = mapped_column(Float, nullable=True)
    bbox_w: Mapped[float | None] = mapped_column(Float, nullable=True)
    bbox_h: Mapped[float | None] = mapped_column(Float, nullable=True)
    zone_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("zones.id"), nullable=True
    )
    person_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("persons.id"), nullable=True
    )
    # Arbitrary extra data (snapshot path, fall angle, etc.)
    payload: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    occurred_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )

    zone: Mapped["Zone | None"] = relationship(back_populates="events")
    person: Mapped["Person | None"] = relationship(back_populates="events")
    alerts: Mapped[list["Alert"]] = relationship(
        back_populates="event", cascade="all, delete-orphan"
    )


# ── Alerts ────────────────────────────────────────────────────────────────────

class Alert(Base):
    __tablename__ = "alerts"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    event_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("events.id", ondelete="CASCADE"),
        nullable=False,
    )
    # "email" | "webhook"
    alert_type: Mapped[str] = mapped_column(String(50), nullable=False)
    recipient: Mapped[str | None] = mapped_column(String(500), nullable=True)
    # "pending" | "sent" | "failed"
    status: Mapped[str] = mapped_column(
        String(50), nullable=False, default="pending"
    )
    attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    last_attempt_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    sent_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )

    event: Mapped["Event"] = relationship(back_populates="alerts")


# ── Camera configs ────────────────────────────────────────────────────────────

class CameraConfig(Base):
    __tablename__ = "camera_configs"
    __table_args__ = (
        UniqueConstraint("camera_id", name="uq_camera_configs_camera_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    camera_id: Mapped[str] = mapped_column(String(255), nullable=False)
    confidence_threshold: Mapped[float | None] = mapped_column(Float, nullable=True)
    iou_threshold: Mapped[float | None] = mapped_column(Float, nullable=True)
    frame_period: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # Active zone IDs for this camera: ["uuid1", "uuid2"]
    zone_ids: Mapped[list | None] = mapped_column(JSONB, nullable=True)
    # Arbitrary per-camera overrides passed to the inference loop
    extra: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )
