"""
S P1.3 — Outbox worker
======================
Non-blocking background worker that drains an in-memory asyncio.Queue and:
  1. Persists events to PostgreSQL (via DAL)
  2. Uploads JPEG snapshots to MinIO / S3
  3. Sends email alerts for fall events (if SMTP is configured)

Enqueue path (sync → async bridge):
  - /infer runs in a thread-pool worker (sync FastAPI endpoint).
  - It calls `enqueue_event()` which uses `loop.call_soon_threadsafe` to
    safely push items onto the asyncio.Queue without blocking.

Queue overflow policy:
  - Queue is bounded (OUTBOX_MAX_SIZE = 1000).
  - If full, the *oldest* item is dropped (put_nowait would raise; we
    drain one slot first).  This matches the plugin drop-oldest policy.
"""

from __future__ import annotations

import asyncio
import io
import json
import logging
import smtplib
import sqlite3
import threading
import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

logger = logging.getLogger(__name__)

# ── tunables ────────────────────────────────────────────────────────────────
OUTBOX_MAX_SIZE = 1000          # items; oldest dropped when full
WORKER_DRAIN_TIMEOUT = 3.0      # seconds to wait for next item before looping
MINIO_SNAPSHOT_PREFIX = "snapshots"
MINIO_CONTENT_TYPE = "image/jpeg"


# ── data types ──────────────────────────────────────────────────────────────

@dataclass
class OutboxEvent:
    """One event generated by the /infer pipeline."""
    camera_id: str
    event_type: str                     # "fall" | "detection" | "zone_violation" | "prolonged"
    occurred_at: datetime
    event_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    track_id: Optional[int] = None
    cls: str = "person"
    confidence: float = 0.0
    bbox_x: float = 0.0                # pixel coords, relative to input frame
    bbox_y: float = 0.0
    bbox_w: float = 0.0
    bbox_h: float = 0.0
    snapshot_jpeg: Optional[bytes] = None   # event review snapshot (fall/zone/detection)
    zone_id: Optional[str] = None           # P2.2: zone that was violated
    # Identity resolved at infer time (real-time face recognition). When present,
    # the event is persisted already linked to a person and alerts use the name.
    person_id: Optional[str] = None
    person_name: Optional[str] = None


# ── module-level state ───────────────────────────────────────────────────────

_loop: Optional[asyncio.AbstractEventLoop] = None
_worker_task: Optional[asyncio.Task] = None
_db: Optional[sqlite3.Connection] = None
_db_lock = threading.Lock()
_wakeup: Optional[asyncio.Event] = None

# Backoff schedule (seconds) indexed by attempt count.
_BACKOFF_SCHEDULE = [1, 2, 5, 10, 30, 60, 120, 300]
_POLL_INTERVAL_SEC = 5.0

# counters exposed to /metrics
_stats: dict = {
    "enqueued": 0,
    "dropped": 0,
    "processed": 0,
    "db_errors": 0,
    "s3_errors": 0,
    "email_errors": 0,
    "emails_sent": 0,
    "retries": 0,
}


def get_stats() -> dict:
    stats = dict(_stats)
    stats["pending"] = _pending_count()
    return stats


# ── SQLite durable store ──────────────────────────────────────────────────────

def _init_db() -> None:
    """Open (and create) the durable outbox SQLite database in WAL mode."""
    global _db
    from .config import OUTBOX_DB_PATH

    _db = sqlite3.connect(OUTBOX_DB_PATH, check_same_thread=False)
    _db.execute("PRAGMA journal_mode=WAL;")
    _db.execute("PRAGMA synchronous=NORMAL;")
    _db.execute(
        """
        CREATE TABLE IF NOT EXISTS outbox_jobs (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            event_id        TEXT NOT NULL,
            payload         TEXT NOT NULL,
            snapshot        BLOB,
            attempts        INTEGER NOT NULL DEFAULT 0,
            next_attempt_at REAL NOT NULL DEFAULT 0,
            created_at      REAL NOT NULL
        )
        """
    )
    _db.execute("CREATE INDEX IF NOT EXISTS ix_outbox_due ON outbox_jobs(next_attempt_at);")
    _db.commit()


def _pending_count() -> int:
    if _db is None:
        return 0
    try:
        with _db_lock:
            cur = _db.execute("SELECT COUNT(*) FROM outbox_jobs")
            return int(cur.fetchone()[0])
    except Exception:
        return 0


def _event_to_payload(event: OutboxEvent) -> str:
    return json.dumps({
        "camera_id": event.camera_id,
        "event_type": event.event_type,
        "occurred_at": event.occurred_at.isoformat(),
        "event_id": event.event_id,
        "track_id": event.track_id,
        "cls": event.cls,
        "confidence": event.confidence,
        "bbox_x": event.bbox_x,
        "bbox_y": event.bbox_y,
        "bbox_w": event.bbox_w,
        "bbox_h": event.bbox_h,
        "zone_id": event.zone_id,
        "person_id": event.person_id,
        "person_name": event.person_name,
    })


def _payload_to_event(payload: str, snapshot: Optional[bytes]) -> OutboxEvent:
    d = json.loads(payload)
    return OutboxEvent(
        camera_id=d["camera_id"],
        event_type=d["event_type"],
        occurred_at=datetime.fromisoformat(d["occurred_at"]),
        event_id=d["event_id"],
        track_id=d.get("track_id"),
        cls=d.get("cls", "person"),
        confidence=d.get("confidence", 0.0),
        bbox_x=d.get("bbox_x", 0.0),
        bbox_y=d.get("bbox_y", 0.0),
        bbox_w=d.get("bbox_w", 0.0),
        bbox_h=d.get("bbox_h", 0.0),
        snapshot_jpeg=bytes(snapshot) if snapshot is not None else None,
        zone_id=d.get("zone_id"),
        person_id=d.get("person_id"),
        person_name=d.get("person_name"),
    )


# ── public init / lifecycle ──────────────────────────────────────────────────

def init_outbox(loop: asyncio.AbstractEventLoop) -> None:
    """Called at service startup (inside async context) to open the durable store."""
    global _loop, _wakeup
    from .config import OUTBOX_DB_PATH

    _loop = loop
    _wakeup = asyncio.Event()
    _init_db()
    pending = _pending_count()
    logger.info(
        "[outbox] Initialised durable store (db=%s, pending=%d)",
        OUTBOX_DB_PATH, pending,
    )


async def start_worker() -> None:
    """Create and store the background asyncio worker task."""
    global _worker_task
    if _worker_task is not None:
        return
    _worker_task = asyncio.create_task(_worker_loop(), name="outbox-worker")
    logger.info("[outbox] Worker task started")


async def stop_worker(drain_timeout: float = 5.0) -> None:
    """Gracefully stop the worker, attempting to drain pending jobs first."""
    global _worker_task
    if _worker_task is None:
        return
    # Give the worker a brief window to flush due jobs.
    deadline = asyncio.get_event_loop().time() + drain_timeout
    while _pending_count() > 0 and asyncio.get_event_loop().time() < deadline:
        if _wakeup is not None:
            _wakeup.set()
        await asyncio.sleep(0.2)
    _worker_task.cancel()
    try:
        await _worker_task
    except asyncio.CancelledError:
        pass
    _worker_task = None
    if _db is not None:
        with _db_lock:
            _db.commit()
    logger.info("[outbox] Worker stopped (pending=%d)", _pending_count())


# ── enqueue (called from sync /infer thread) ─────────────────────────────────

def enqueue_event(event: OutboxEvent) -> None:
    """Durably persist an event to the local SQLite outbox, then wake the worker.

    Runs in the sync /infer thread. Never blocks on network I/O — only a fast
    local SQLite insert. Events survive a service restart/crash and are replayed.
    Applies a drop-oldest cap to bound disk usage under sustained backlog.
    """
    if _db is None or _loop is None:
        return
    try:
        from .metrics import OUTBOX_ENQUEUED, OUTBOX_DROPPED

        payload = _event_to_payload(event)
        with _db_lock:
            # Drop-oldest cap (matches the plugin's drop-oldest backpressure policy).
            count = int(_db.execute("SELECT COUNT(*) FROM outbox_jobs").fetchone()[0])
            if count >= OUTBOX_MAX_SIZE:
                _db.execute(
                    "DELETE FROM outbox_jobs WHERE id IN "
                    "(SELECT id FROM outbox_jobs ORDER BY id ASC LIMIT 1)"
                )
                _stats["dropped"] += 1
                OUTBOX_DROPPED.inc()
            _db.execute(
                "INSERT INTO outbox_jobs (event_id, payload, snapshot, attempts, next_attempt_at, created_at) "
                "VALUES (?, ?, ?, 0, 0, ?)",
                (event.event_id, payload, event.snapshot_jpeg, time.time()),
            )
            _db.commit()

        _stats["enqueued"] += 1
        OUTBOX_ENQUEUED.inc()
        # Wake the async worker from this (sync) thread.
        if _wakeup is not None:
            _loop.call_soon_threadsafe(_wakeup.set)
    except Exception as exc:
        logger.warning("[outbox] enqueue_event failed: %s", exc)


# ── worker loop ──────────────────────────────────────────────────────────────

def _fetch_due_jobs(limit: int = 20) -> list[tuple]:
    """Return [(id, payload, snapshot, attempts)] for jobs whose backoff elapsed."""
    if _db is None:
        return []
    now = time.time()
    with _db_lock:
        cur = _db.execute(
            "SELECT id, payload, snapshot, attempts FROM outbox_jobs "
            "WHERE next_attempt_at <= ? ORDER BY id ASC LIMIT ?",
            (now, limit),
        )
        return cur.fetchall()


def _delete_job(job_id: int) -> None:
    if _db is None:
        return
    with _db_lock:
        _db.execute("DELETE FROM outbox_jobs WHERE id = ?", (job_id,))
        _db.commit()


def _reschedule_job(job_id: int, attempts: int) -> bool:
    """Bump attempts and set next_attempt_at via backoff. Returns False if dropped."""
    if _db is None:
        return False
    from .config import OUTBOX_MAX_ATTEMPTS

    new_attempts = attempts + 1
    with _db_lock:
        if new_attempts >= OUTBOX_MAX_ATTEMPTS:
            _db.execute("DELETE FROM outbox_jobs WHERE id = ?", (job_id,))
            _db.commit()
            return False
        backoff = _BACKOFF_SCHEDULE[min(new_attempts - 1, len(_BACKOFF_SCHEDULE) - 1)]
        _db.execute(
            "UPDATE outbox_jobs SET attempts = ?, next_attempt_at = ? WHERE id = ?",
            (new_attempts, time.time() + backoff, job_id),
        )
        _db.commit()
    return True


async def _worker_loop() -> None:
    logger.info("[outbox] Worker loop running (durable SQLite)")
    while True:
        try:
            jobs = await asyncio.to_thread(_fetch_due_jobs, 20)

            if not jobs:
                # Nothing due — sleep until woken or the poll interval elapses.
                if _wakeup is not None:
                    try:
                        await asyncio.wait_for(_wakeup.wait(), timeout=_POLL_INTERVAL_SEC)
                    except asyncio.TimeoutError:
                        pass
                    _wakeup.clear()
                else:
                    await asyncio.sleep(_POLL_INTERVAL_SEC)
                continue

            for job_id, payload, snapshot, attempts in jobs:
                try:
                    event = _payload_to_event(payload, snapshot)
                except Exception as exc:
                    logger.error("[outbox] Corrupt job %s dropped: %s", job_id, exc)
                    await asyncio.to_thread(_delete_job, job_id)
                    continue

                try:
                    await _process_event(event)
                    await asyncio.to_thread(_delete_job, job_id)
                    _stats["processed"] += 1
                    from .metrics import OUTBOX_PROCESSED, OUTBOX_PENDING
                    OUTBOX_PROCESSED.inc()
                    OUTBOX_PENDING.set(float(_pending_count()))
                except Exception as exc:
                    kept = await asyncio.to_thread(_reschedule_job, job_id, attempts)
                    _stats["retries"] += 1
                    if kept:
                        logger.warning(
                            "[outbox] Event %s failed (attempt %d) — will retry: %s",
                            event.event_id, attempts + 1, exc,
                        )
                    else:
                        logger.error(
                            "[outbox] Event %s dropped after max attempts: %s",
                            event.event_id, exc,
                        )
        except asyncio.CancelledError:
            logger.info("[outbox] Worker loop cancelled")
            return
        except Exception as exc:
            logger.error("[outbox] Worker loop error: %s", exc, exc_info=True)
            await asyncio.sleep(1.0)


async def _process_event(event: OutboxEvent) -> None:
    """Persist → MinIO + alert (persist first for idempotency; upload & alert run in parallel)."""
    from . import alert_engine
    from .config import (
        ALERT_FALL_ENABLED, ALERT_ZONE_VIOLATION_ENABLED,
        SMTP_HOST, ALERT_EMAIL_TO,
    )

    # Step 1: DB first (idempotent)
    db_event_pk = await _persist_event(event)

    # Step 2+3: upload snapshot and send alert in parallel
    fan_out: list = []
    if event.snapshot_jpeg:
        fan_out.append(_upload_snapshot(event))

    # S P2.3 — route alert through alert_engine (retry + dedupe + rate limit)
    if event.event_type == "fall" and ALERT_FALL_ENABLED and SMTP_HOST and ALERT_EMAIL_TO:
        fan_out.append(alert_engine.send_alert(event, db_event_pk))
    elif event.event_type == "zone_violation" and ALERT_ZONE_VIOLATION_ENABLED and SMTP_HOST and ALERT_EMAIL_TO:
        fan_out.append(alert_engine.send_alert(event, db_event_pk))

    # S P2.1 — auto-link event to a known person via ReID (best-effort, non-blocking)
    from .config import REID_AUTO_LINK_ENABLED
    if (
        REID_AUTO_LINK_ENABLED
        and db_event_pk is not None
        and event.person_id is None          # not already identified at infer time
        and event.snapshot_jpeg
        and event.event_type in ("fall", "zone_violation")
    ):
        from . import reid_service
        fan_out.append(reid_service.try_auto_link_event(db_event_pk))

    if fan_out:
        results = await asyncio.gather(*fan_out, return_exceptions=True)
        for r in results:
            if isinstance(r, Exception):
                logger.debug("[outbox] Fan-out sub-task error (already logged): %s", r)


# ── step 1: persist to PostgreSQL ────────────────────────────────────────────

async def _persist_event(event: OutboxEvent) -> "uuid.UUID | None":
    """Persist event + optional alert record.  Returns internal DB UUID of the event."""
    from .db import get_session
    from .db import dal
    from .config import (
        ALERT_EMAIL_TO, ALERT_FALL_ENABLED,
        ALERT_ZONE_VIOLATION_ENABLED, SMTP_HOST,
    )

    try:
        async with get_session() as session:
            snapshot_key = _snapshot_key(event) if event.snapshot_jpeg else None
            payload: dict | None = {"snapshot_key": snapshot_key} if snapshot_key else None

            import uuid as _uuid_mod
            zone_uuid = None
            if event.zone_id:
                try:
                    zone_uuid = _uuid_mod.UUID(event.zone_id)
                except (ValueError, AttributeError):
                    pass

            person_uuid = None
            if event.person_id:
                try:
                    person_uuid = _uuid_mod.UUID(str(event.person_id))
                except (ValueError, AttributeError):
                    pass

            db_event = await dal.upsert_event(
                session,
                event_id=event.event_id,
                camera_id=event.camera_id,
                event_type=event.event_type,
                track_id=event.track_id,
                cls=event.cls,
                confidence=event.confidence,
                bbox_x=event.bbox_x,
                bbox_y=event.bbox_y,
                bbox_w=event.bbox_w,
                bbox_h=event.bbox_h,
                zone_id=zone_uuid,
                person_id=person_uuid,
                payload=payload,
                occurred_at=event.occurred_at,
            )

            # Pre-create alert rows for alert-eligible event types
            alert_pk = None
            needs_alert = (
                (event.event_type == "fall" and ALERT_FALL_ENABLED) or
                (event.event_type == "zone_violation" and ALERT_ZONE_VIOLATION_ENABLED)
            )
            if needs_alert and SMTP_HOST and ALERT_EMAIL_TO:
                alert = await dal.create_alert(
                    session,
                    event_id=db_event.id,
                    alert_type="email",
                    recipient=ALERT_EMAIL_TO,
                    status="pending",
                )
                alert_pk = alert.id

            pk = db_event.id
        logger.debug("[outbox] Event %s persisted (type=%s, camera=%s)", event.event_id, event.event_type, event.camera_id)
        try:
            from .metrics import EVENTS_PERSISTED
            EVENTS_PERSISTED.labels(event_type=event.event_type, camera_id=event.camera_id).inc()
        except Exception:
            pass
        return pk
    except Exception as exc:
        _stats["db_errors"] += 1
        try:
            from .metrics import OUTBOX_ERRORS
            OUTBOX_ERRORS.labels(kind="db").inc()
        except Exception:
            pass
        logger.warning("[outbox] DB persist failed for %s: %s", event.event_id, exc)
        raise


# ── step 2: upload snapshot to MinIO ─────────────────────────────────────────

def _snapshot_key(event: OutboxEvent) -> str:
    date_str = event.occurred_at.strftime("%Y/%m/%d")
    return f"{MINIO_SNAPSHOT_PREFIX}/{event.camera_id}/{date_str}/{event.event_id}.jpg"


async def _upload_snapshot(event: OutboxEvent) -> None:
    if not event.snapshot_jpeg:
        return

    from .config import S3_ENDPOINT, S3_ACCESS_KEY, S3_SECRET_KEY, S3_BUCKET_SNAPSHOTS, S3_REGION

    if not S3_ENDPOINT or not S3_ACCESS_KEY:
        return

    key = _snapshot_key(event)
    jpeg_bytes = event.snapshot_jpeg

    try:
        await asyncio.to_thread(_s3_put_object, S3_ENDPOINT, S3_ACCESS_KEY, S3_SECRET_KEY, S3_BUCKET_SNAPSHOTS, S3_REGION, key, jpeg_bytes)
        logger.debug("[outbox] Snapshot uploaded: s3://%s/%s", S3_BUCKET_SNAPSHOTS, key)
    except Exception as exc:
        _stats["s3_errors"] += 1
        try:
            from .metrics import OUTBOX_ERRORS
            OUTBOX_ERRORS.labels(kind="s3").inc()
        except Exception:
            pass
        logger.warning("[outbox] MinIO upload failed for %s: %s", key, exc)
        raise


def _s3_put_object(
    endpoint: str,
    access_key: str,
    secret_key: str,
    bucket: str,
    region: str,
    key: str,
    data: bytes,
) -> None:
    """Synchronous S3 put; runs inside asyncio.to_thread."""
    import boto3
    from botocore.config import Config as BotoConfig

    # Strip trailing slash from endpoint
    endpoint = endpoint.rstrip("/")
    use_ssl = endpoint.startswith("https://")

    client = boto3.client(
        "s3",
        endpoint_url=endpoint,
        aws_access_key_id=access_key,
        aws_secret_access_key=secret_key,
        region_name=region,
        config=BotoConfig(signature_version="s3v4"),
        use_ssl=use_ssl,
    )
    # Ensure bucket exists (idempotent)
    try:
        client.head_bucket(Bucket=bucket)
    except Exception:
        try:
            client.create_bucket(Bucket=bucket)
        except Exception:
            pass  # might already exist or race condition; upload anyway

    client.put_object(
        Bucket=bucket,
        Key=key,
        Body=io.BytesIO(data),
        ContentType=MINIO_CONTENT_TYPE,
    )


# ── step 3: email alert ───────────────────────────────────────────────────────

async def _send_alert_email(event: OutboxEvent, db_event_pk: "uuid.UUID | None" = None) -> None:
    from .config import (
        SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD,
        SMTP_FROM, ALERT_EMAIL_TO, ALERT_FALL_ENABLED,
    )

    if not ALERT_FALL_ENABLED or not SMTP_HOST or not ALERT_EMAIL_TO:
        return

    now = datetime.now(tz=timezone.utc)
    success = False
    try:
        await asyncio.to_thread(
            _smtp_send,
            SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD,
            SMTP_FROM, ALERT_EMAIL_TO, event,
        )
        _stats["emails_sent"] += 1
        success = True
        logger.info("[outbox] Fall-alert email sent to %s (event=%s, camera=%s, track=%s)",
                    ALERT_EMAIL_TO, event.event_id, event.camera_id, event.track_id)
    except Exception as exc:
        _stats["email_errors"] += 1
        try:
            from .metrics import OUTBOX_ERRORS
            OUTBOX_ERRORS.labels(kind="email").inc()
        except Exception:
            pass
        logger.warning("[outbox] Email send failed for %s: %s", event.event_id, exc)
    finally:
        # Update alert row status in DB (best-effort; don't raise)
        if db_event_pk is not None:
            try:
                await _update_alert_status(db_event_pk, success=success, attempted_at=now)
            except Exception as db_exc:
                logger.debug("[outbox] Alert status update failed: %s", db_exc)
    if not success:
        raise RuntimeError("Email send failed (see earlier log)")


async def _update_alert_status(db_event_pk: "uuid.UUID", *, success: bool, attempted_at: datetime) -> None:
    from .db import get_session, dal

    async with get_session() as session:
        await dal.record_email_alert_attempt(
            session,
            db_event_pk,
            success=success,
            attempted_at=attempted_at,
        )


def _smtp_send(
    host: str,
    port: int,
    user: str,
    password: str,
    from_addr: str,
    to_addr: str,
    event: OutboxEvent,
) -> None:
    """Synchronous SMTP send; runs inside asyncio.to_thread."""
    ts = event.occurred_at.strftime("%Y-%m-%d %H:%M:%S UTC")
    subject = f"[SafeAging ALERT] Fall detected — {event.camera_id}"
    body_text = (
        f"Fall detection alert\n"
        f"====================\n"
        f"Camera  : {event.camera_id}\n"
        f"Track ID: {event.track_id}\n"
        f"Time    : {ts}\n"
        f"Confidence: {event.confidence:.0%}\n"
        f"Event ID: {event.event_id}\n"
    )
    if event.snapshot_jpeg:
        key = _snapshot_key(event)
        body_text += f"Snapshot: {key}\n"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = to_addr
    msg.attach(MIMEText(body_text, "plain"))

    # TLS on port 465, STARTTLS otherwise
    if port == 465:
        with smtplib.SMTP_SSL(host, port, timeout=10) as server:
            if user:
                server.login(user, password)
            server.sendmail(from_addr, [to_addr], msg.as_string())
    else:
        with smtplib.SMTP(host, port, timeout=10) as server:
            server.ehlo()
            try:
                server.starttls()
                server.ehlo()
            except smtplib.SMTPNotSupportedError:
                pass
            if user:
                server.login(user, password)
            server.sendmail(from_addr, [to_addr], msg.as_string())
